jdk:
  - openjdk8
  - openjdk11
language: scala
script: sbt clean compile coverage test
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
sudo: false
